### ISSUE TITLE
Linux version thinks smash_arc isn't there when it is

### ISSUE THREAD

**Issue by Roadhog360** [ScanMountGoat/ArcExplorer#63]
I have installed the .NET Core 3.1 runtime successfully (which the Linux instructions default the commands to 6.0, you should note you have to edit Microsoft's commands and replace 6.0 with 3.1.)
However, nowhere in the readme or download is smash_arc mentioned, so I assume the .so files included were enough. However, clearly I need to download more as the program does not launch and says something from it is missing. Am I supposed to have more than this single .so file that was included in your download?
![image](https://user-images.githubusercontent.com/11903511/143793925-c5235cf5-0813-479c-b5a5-107b98134db5.png)
`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'smash_arc' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsmash_arc: cannot open shared object file: No such file or directory
   at SmashArcNet.RustBindings.ArcLoadLabels(String path)
   at SmashArcNet.HashLabels.TryLoadHashes(String path)
   at ArcExplorer.ViewModels.MainWindowViewModel..ctor() in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\ViewModels\MainWindowViewModel.cs:line 201
   at ArcExplorer.App.OnFrameworkInitializationCompleted() in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\App.axaml.cs:line 30
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 178
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 149
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 117
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at ArcExplorer.Program.Main(String[] args) in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\Program.cs:line 11
`

**Comment by ScanMountGoat** [comment]
Every Linux build is tested prior to release, so all the necessary files are there. ArcExplorer 0.14 opens just fine for me on Ubuntu 21.04. Which version of Linux are you using?

**Comment by Roadhog360** [comment]
Ubuntu 20.04

**Comment by Roadhog360** [comment]
Since you have confirmed all needed files are included, I have chnaged the title.

**Comment by ScanMountGoat** [comment]
I'll see if I can reproduce this on a clean install of Ubuntu 20.04.

**Comment by ScanMountGoat** [comment]
I'm able to reproduce this on my end on a Linux VM. I'll let you know if I figure out why this isn't working.

**Comment by ScanMountGoat** [comment]
@Roadhog360 This should be fixed on the latest release (1.4.1). It's working fine for me on a clean install of Ubuntu 20.04. Let me know if you're still having issues.

**Comment by Roadhog360** [comment]
Phew, thanks. I was worried you wouldn't be able to get the same issue. Hopefully you're able to find a fix, thanks for checking it out.

**Comment by ScanMountGoat** [comment]
That would be great. Thanks

**Comment by Roadhog360** [comment]
Seems the new release fixes it, I can open, and extract files just fine.

**Comment by Roadhog360** [comment]
Since this is closed now, is it okay if I ask if there are any better alternatives to Toolbox? It seems to run in Wine, but only the 32-bit version and I noticed import previews just don't work, I have to actually replace or add the image to see how it looks.

**Comment by ScanMountGoat** [comment]
That's not on topic for this repository. You're better off asking on the switch toolbox repo itself. The short answer is that nothing else does most of the features of Switch Toolbox. The code in switch toolbox isn't particularly portable, sadly.

If you just want to make convert nutexb files on linux, there are some WIP command line tools written in Rust that work with a bit more development work. If people are interested, I may work on patching img2nutexb to fully support all the nutexb files in Smash Ultimate. It can be compiled for a lot of platforms like windows, mac, etc.
tool: https://github.com/jam1garner/img2nutexb
library: https://github.com/jam1garner/nutexb
