### ISSUE TITLE
ArcExplorer linux refuses to launch

### ISSUE THREAD

**Issue by remivamp** [ScanMountGoat/ArcExplorer#65]
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'smash_arc' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsmash_arc: cannot open shared object file: No such file or directory
   at SmashArcNet.RustBindings.ArcLoadLabels(String path)
   at SmashArcNet.HashLabels.TryLoadHashes(String path)
   at ArcExplorer.ViewModels.MainWindowViewModel..ctor() in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\ViewModels\MainWindowViewModel.cs:line 201
   at ArcExplorer.App.OnFrameworkInitializationCompleted() in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\App.axaml.cs:line 30
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 178
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 149
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 117
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at ArcExplorer.Program.Main(String[] args) in C:\Users\Jonathan\Documents\GITHUB\ArcExplorer\ArcExplorer\Program.cs:line 11
Aborted (core dumped)

This is the error I get whenever I run arcexplorer on my Linux Mint Debian Edition 4 machine.

**Comment by ScanMountGoat** [comment]
This is probably the same as #63. Thanks for including what distro you're using. I can reproduce this on a clean ubuntu install as well but haven't figure out what the issue is yet.

**Comment by ScanMountGoat** [comment]
This appears to be an issue with the Rust binaries missing some runtime components (glibc). I'll look into updating the linux builds to avoid this.

**Comment by ScanMountGoat** [comment]
@remivamp what output do you get when running `ldd --version` in your terminal? The current linux build was built using glibc 2.33.

**Comment by remivamp** [comment]
ldd (Debian GLIBC 2.28-10) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

It's based on debian 10 so that's why it's an older GLibC

**Comment by ScanMountGoat** [comment]
@remivamp Let me know if version 1.4.1 is working for you. You shouldn't need to install anything. I haven't tested on Linux Mint Debian, but it's working for me on a clean install of Ubuntu 20.04.

**Comment by remivamp** [comment]
It launches. that fixed it.
